language: python


python:
  - 3.6


install:
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt


script:
 - bash run_tests.sh


after_success:
  - coveralls --data_file .coverage
