name: patapy
channels:
 - conda-forge
 - anaconda
 - bioconda
dependencies:
 - pip:
   - sphinx-autodoc-typehints
   - sphinx-autodoc-annotation
 - python=3.6
 - pandas
 - numpy
 - statsmodels
 - scipy
 - bioservices
 - networkx